### ISSUE TITLE
UTMP_FILE does not exist

### ISSUE THREAD

**Issue by hexaheximal** [slicer69/sysvinit#20] opened 2023-08-28 11:05 UTC
So, I was building Gentoo yesterday and sys-apps/sysvinit (3.07) failed with this:

```
In file included from init.c:59:
init.c: In function ‘redo_utmp_wtmp’:
init.c:2326:30: error: ‘_PATH_UTMP’ undeclared (first use in this function)
 2326 |         const int ret = stat(UTMP_FILE, &ustat);
      |                              ^~~~~~~~~
init.c:2326:30: note: each undeclared identifier is reported only once for each function it appears in
init.c: In function ‘init_main’:
init.c:2883:24: error: ‘_PATH_UTMP’ undeclared (first use in this function)
 2883 |         if ((fd = open(UTMP_FILE, O_WRONLY|O_CREAT|O_TRUNC, 0644)) >= 0)
      |                        ^~~~~~~~~
make[1]: *** [<builtin>: init.o] Error 1
```

Searching for `UTMP_FILE` via grep only shows references - the only declaration is behind a freebsd ifdef. (see: init.h)

I also tried searching for `_PATH_UTMP`, but there are no references at all, so I don't even know why the compiler error mentions it.

Is this just me or is this reproducable on all machines? Is this bitrot?

**Comment by slicer69** [comment] 2023-08-28 14:43
It's hard to tell from this snippet, but it looks like the compiler is unable to find utmp.h or the utmp.h on your system (or one of the headers it relies on) doesn't declare _PATH_UTMP.

This could be a case of a missing development package causing missing headers, or headers changing since the last build due to features being removed from a package.

Typically init.c pulls in utmp.h which, in turn will pull in some headers such as paths.h. On my system paths.h is where _PATH_UTMP is declared. 

It may be that, on Gentoo, we might need to explicitly include paths.h from init.c.  Could you try that, add the line

      #include <paths.h>

near the top of init.c and see if it builds?

**Comment by hexaheximal** [comment] 2023-08-28 20:06
So, after checking I can indeed confirm that /usr/include/paths.h does exist in the Gentoo rootfs.

I've also been able to reproduce this on my Debian machine, which does have that file too.

I have no idea how to edit the code in a Gentoo package though...

**Comment by slicer69** [comment] 2023-08-28 20:18
You're saying the compile attempt fails on Debian? This is interesting because I use Debian as one of the test platforms where I build and run init. Which version of Debian are you running?

Could you provide more complete output showing the steps you are using to fetch the source code and build it? Maybe that will provide a clue where things are going wrong.

**Comment by hexaheximal** [comment] 2023-08-28 20:22
Correct, it fails on Debian (bookworm more specifically) too. I'm trying to install Gentoo on a separate disk but the same machine.

For Gentoo, it's just emege with the default use flags, nothing special.

On Debian, I built it from source by running `git clone https://github.com/slicer69/sysvinit` and running `make` in the directory where the makefile is.

**Comment by slicer69** [comment] 2023-08-28 20:43
Just to make sure we're on the same page, each directory has its own Makefile. Are you running "make" in the top-level directory or the "src" directory?

**Comment by hexaheximal** [comment] 2023-08-28 22:46
> Are you running "make" in the top-level directory or the "src" directory?

top-level

> Edit: Could you please confirm that the "build-essential" package is installed on your Debian system?

yes, I do have build-essential

**Comment by slicer69** [comment] 2023-08-29 00:12
Can you add the "#include <paths.h>" line I suggested before to the src/init.c file on the Debian machine? I'm curious if that works.

**Comment by hexaheximal** [comment] 2023-08-29 11:09
Same error, even after adding that.

**Comment by slicer69** [comment] 2023-08-31 14:57
In the original report you mentioned building sysvinit on Gentoo. and it sounds like you're building it from the port, not doing it manually. Have you reported the issue to Gentoo's bug tracker? I looked for any issues there and didn't find mention of it not building and it looks like 3.07 has been tested and confirmed working for most architectures Gentoo supports.

**Comment by hexaheximal** [comment] 2023-09-01 12:31
I haven't submitted a bug to the Gentoo issue tracker.

One thing I'm thinking about is the possibility of this being related to environment variables - I've found trailing colons in CPATH, LIBRARY_PATH, and LD_LIBRARY PATH, and that seems to have caused multiple packages to not build.

**Comment by slicer69** [comment] 2023-09-01 14:56
Just to make sure I'm clear on the variable situations, you're saying the environment variables on your system have trailing colons? Not variables set in the Makefiles of these projects?

**Comment by hexaheximal** [comment] 2023-09-01 15:37
Correct. Both the Gentoo chroot and host Debian system does.

**Comment by slicer69** [comment] 2023-09-01 15:41
This is interesting. If the colons are removed from the variables is sysvinit able to compile?

**Comment by hexaheximal** [comment] 2023-09-01 15:43
yes, unsetting CPATH, LIBRARY_PATH, and LD_LIBRARY_PATH seems to have completely fixed it :thinking:

**Comment by slicer69** [comment] 2023-09-01 18:43
Interesting. I'm going to close this. If the environment variables you encountered were the defaults for your distribution(s), perhaps you could report this as an issue so it doesn't take other people by surprise?

**Closed by slicer69** 2023-09-01 18:43 UTC
